import type { EngineResponse, EventAction, EventCondition, GeneratedWorld, RunState } from "../core/types.js";
function keyForRead(hostId: string, path: string): string { return `${hostId}:${path}`; }
function currentFrame(state: RunState) { return state.sessionStack[state.sessionStack.length - 1]!; }
function matches(condition: EventCondition, state: RunState): boolean { const frame = currentFrame(state); switch (condition.type) { case "fileRead": return state.readFiles.includes(keyForRead(condition.hostId, condition.path)); case "flag": return state.flags.includes(condition.flag); case "hostDiscovered": return state.discoveredHosts.includes(condition.hostId); case "currentUser": return frame.username === condition.username && (!condition.hostId || frame.hostId === condition.hostId); case "rootOn": return state.rootedHosts.includes(condition.hostId); case "commandExecuted": return state.commandLog.some((entry) => { const [hostId, command] = entry.split("::", 2); return command === condition.command && (!condition.hostId || condition.hostId === hostId); }); } }
function uniquePush(values: string[], value: string): void { if (!values.includes(value)) values.push(value); }
function applyAction(action: EventAction, state: RunState, response: EngineResponse): void { switch (action.type) { case "setFlag": uniquePush(state.flags, action.flag); break; case "discoverHost": uniquePush(state.discoveredHosts, action.hostId); break; case "learnCredential": uniquePush(state.knownCredentials, action.credentialId); break; case "output": response.lines.push(...action.lines); break; case "achievement": uniquePush(state.achievements, action.id); response.lines.push("", `ACHIEVEMENT UNLOCKED: ${action.id.toUpperCase()}`); break; case "ending": state.ending = { id: action.id, title: action.title }; break; case "spawnProcess": { const list = state.dynamicProcesses[action.hostId] ?? []; if (!list.some((process) => process.pid === action.process.pid)) { list.push({ ...action.process }); state.dynamicProcesses[action.hostId] = list; } break; } } }
export function evaluateEvents(world: GeneratedWorld, state: RunState, response: EngineResponse): void { for (let pass = 0; pass < 16; pass += 1) { let fired = false; for (const event of world.events) { if ((event.once ?? true) && state.firedEvents.includes(event.id)) continue; if (!event.all.every((condition) => matches(condition, state))) continue; if (event.once ?? true) uniquePush(state.firedEvents, event.id); for (const action of event.actions) applyAction(action, state, response); fired = true; } if (!fired) break; } }
export function markFileRead(state: RunState, hostId: string, path: string): void { uniquePush(state.readFiles, keyForRead(hostId, path)); }
export function markRooted(state: RunState, hostId: string): void { uniquePush(state.rootedHosts, hostId); }
