import type { CommandInvocation, EngineResponse, GameHost, GameUser, GeneratedWorld, RunState } from "./types.js";
import { parseCommand } from "../command/parser.js";
import { basename, canExecute, canRead, displayPath, getNode, globToRegExp, listDirectory, modeString, normalizeVirtualPath } from "../vfs/vfs.js";
import { evaluateEvents, markFileRead, markRooted } from "../events/events.js";

const CORE_COMMANDS = ["help","clear","pwd","cd","ls","cat","whoami","id","uname","hostname","history","grep","find","ps","env","su","sudo","ssh","exit","netstat","mail","system"] as const;
function uniquePush(values: string[], value: string): void { if (!values.includes(value)) values.push(value); }
function initialState(world: GeneratedWorld): RunState { return { stateVersion:1, sessionStack:[{hostId:world.startHostId,username:null,cwd:"/"}], mode:{kind:"login-user"}, history:[], flags:[], discoveredHosts:[world.startHostId], knownCredentials:[], readFiles:[], firedEvents:[], achievements:[], rootedHosts:[], dynamicProcesses:{}, commandLog:[], commandCount:0 }; }

export class GameEngine {
  readonly world: GeneratedWorld; state: RunState;
  constructor(world: GeneratedWorld, restoredState?: RunState) { this.world = world; this.state = restoredState ? structuredClone(restoredState) : initialState(world); this.repairRestoredState(); }
  private repairRestoredState(): void { if (this.state.sessionStack.length === 0) { this.state.sessionStack.push({hostId:this.world.startHostId,username:null,cwd:"/"}); this.state.mode={kind:"login-user"}; } this.state.discoveredHosts ??= [this.world.startHostId]; uniquePush(this.state.discoveredHosts,this.world.startHostId); }
  get frame() { return this.state.sessionStack[this.state.sessionStack.length-1]!; }
  get host(): GameHost { const host=this.world.hosts[this.frame.hostId]; if(!host) throw new Error(`active host not found: ${this.frame.hostId}`); return host; }
  get user(): GameUser|null { if(!this.frame.username) return null; return this.host.users[this.frame.username]??null; }
  get maskedInput(): boolean { return ["login-password","su-password","ssh-password"].includes(this.state.mode.kind); }
  prompt(): string { switch(this.state.mode.kind){ case"login-user":return"login: "; case"login-password":case"su-password":return"Password: "; case"ssh-password":return`${this.state.mode.username}@${this.world.hosts[this.state.mode.hostId]?.hostname??this.state.mode.hostId}'s password: `; case"shell":{const user=this.user;if(!user)return"login: ";const cwd=displayPath(this.frame.cwd,user.home);return`${user.username}@${this.host.hostname}:${cwd}${user.uid===0?"#":"$"} `;}} }
  handleInput(input:string):EngineResponse { const value=input.trim();const response:EngineResponse={lines:[]};switch(this.state.mode.kind){case"login-user":return this.handleLoginUser(value);case"login-password":return this.handleLoginPassword(input,this.state.mode.username);case"su-password":return this.handleSuPassword(input,this.state.mode.username);case"ssh-password":return this.handleSshPassword(input,this.state.mode.hostId,this.state.mode.username);case"shell":break;}if(value==="")return response;this.state.history.push(input);this.state.commandCount+=1;let invocation:CommandInvocation|null;try{invocation=parseCommand(input);}catch(error){response.lines.push(`ysh: ${error instanceof Error?error.message:String(error)}`);return response;}if(!invocation)return response;this.state.commandLog.push(`${this.frame.hostId}::${invocation.raw.trim()}`);if(this.state.commandLog.length>200)this.state.commandLog.shift();this.execute(invocation,response);evaluateEvents(this.world,this.state,response);return response; }
  private handleLoginUser(value:string):EngineResponse { if(value==="help"||value==="?")return{lines:["Remote access help:","  Temporary account: guest","  Temporary password: visitor"]};if(value==="")return{lines:[]};if(!this.host.users[value])return{lines:["Login incorrect",""]};this.state.mode={kind:"login-password",username:value};return{lines:[]}; }
  private handleLoginPassword(password:string,username:string):EngineResponse { const user=this.host.users[username];if(!user||user.password!==password){this.state.mode={kind:"login-user"};return{lines:["","Login incorrect",""]};}this.frame.username=username;this.frame.cwd=user.home;this.state.mode={kind:"shell"};if(user.uid===0)markRooted(this.state,this.frame.hostId);return{lines:["",`Last login: UNKNOWN from REMOTE`,`Welcome to ${this.host.os}.`,""]}; }
  private handleSuPassword(password:string,username:string):EngineResponse { const target=this.host.users[username];if(!target||target.password==="!"||target.password!==password){this.state.mode={kind:"shell"};return{lines:["su: Authentication failure"]};}this.frame.username=username;this.frame.cwd=target.home;this.state.mode={kind:"shell"};if(target.uid===0)markRooted(this.state,this.frame.hostId);return{lines:[]}; }
  private handleSshPassword(password:string,hostId:string,username:string):EngineResponse { const targetHost=this.world.hosts[hostId];const targetUser=targetHost?.users[username];if(!targetHost||!targetUser||targetUser.password==="!"||targetUser.password!==password){this.state.mode={kind:"shell"};return{lines:["Permission denied, please try again."]};}this.state.sessionStack.push({hostId,username,cwd:targetUser.home});this.state.mode={kind:"shell"};if(targetUser.uid===0)markRooted(this.state,hostId);return{lines:["",`Connected to ${targetHost.hostname}.`,targetHost.os,""]}; }
  private execute(invocation:CommandInvocation,response:EngineResponse):void { const handlers:Record<string,(args:string[],out:EngineResponse)=>void>={help:(a,o)=>this.cmdHelp(a,o),clear:(_a,o)=>{o.clear=true;},pwd:(_a,o)=>o.lines.push(this.frame.cwd),cd:(a,o)=>this.cmdCd(a,o),ls:(a,o)=>this.cmdLs(a,o),cat:(a,o)=>this.cmdCat(a,o),whoami:(_a,o)=>o.lines.push(this.user?.username??"unknown"),id:(_a,o)=>this.cmdId(o),uname:(a,o)=>this.cmdUname(a,o),hostname:(_a,o)=>o.lines.push(this.host.hostname),history:(_a,o)=>this.state.history.forEach((e,i)=>o.lines.push(`${String(i+1).padStart(4)}  ${e}`)),grep:(a,o)=>this.cmdGrep(a,o),find:(a,o)=>this.cmdFind(a,o),ps:(a,o)=>this.cmdPs(a,o),env:(_a,o)=>this.cmdEnv(o),su:(a,o)=>this.cmdSu(a,o),sudo:(a,o)=>this.cmdSudo(a,o),ssh:(a,o)=>this.cmdSsh(a,o),exit:(_a,o)=>this.cmdExit(o),netstat:(_a,o)=>this.cmdNetstat(o),mail:(_a,o)=>this.cmdMail(o),system:(a,o)=>this.cmdSystem(a,o),diagctl:(a,o)=>this.cmdDiagctl(a,o)};const handler=handlers[invocation.name];const available=CORE_COMMANDS.includes(invocation.name as typeof CORE_COMMANDS[number])||this.host.commands.includes(invocation.name);if(!handler||!available){response.lines.push(`${invocation.name}: command not found`);return;}handler(invocation.args,response); }
  private requireUser(response:EngineResponse):GameUser|null { if(!this.user){response.lines.push("Not logged in.");return null;}return this.user; }
  private resolvePath(input:string|undefined,user:GameUser):string { return normalizeVirtualPath(this.frame.cwd,input??"",user.home); }
  private cmdHelp(_args:string[],response:EngineResponse):void { response.lines.push("Available commands:","  help clear pwd cd ls cat whoami id uname hostname history","  grep find ps env su sudo ssh exit netstat mail system","","Try normal Unix-like commands. Some hosts provide additional utilities."); }
  private cmdCd(args:string[],response:EngineResponse):void { const user=this.requireUser(response);if(!user)return;const path=this.resolvePath(args[0],user);const node=getNode(this.host,path);if(!node)return void response.lines.push(`cd: ${args[0]??""}: No such file or directory`);if(node.type!=="dir")return void response.lines.push(`cd: ${args[0]??path}: Not a directory`);if(!canExecute(node,user))return void response.lines.push(`cd: ${args[0]??path}: Permission denied`);this.frame.cwd=path; }
  private cmdLs(args:string[],response:EngineResponse):void { const user=this.requireUser(response);if(!user)return;const flags=args.filter(a=>a.startsWith("-")).join("");const targetArg=args.find(a=>!a.startsWith("-"));const showAll=flags.includes("a"),long=flags.includes("l");const path=this.resolvePath(targetArg??".",user);const node=getNode(this.host,path);if(!node)return void response.lines.push(`ls: cannot access '${targetArg??path}': No such file or directory`);if(node.type==="file"){response.lines.push(long?this.longListing(basename(path),node):basename(path));return;}if(!canRead(node,user))return void response.lines.push(`ls: cannot open directory '${targetArg??path}': Permission denied`);for(const child of listDirectory(this.host,path)){if(!showAll&&child.name.startsWith("."))continue;response.lines.push(long?this.longListing(child.name,child.node):child.name);} }
  private longListing(name:string,node:NonNullable<ReturnType<typeof getNode>>):string { const size=node.type==="file"?(node.content?.length??0):4096;return`${modeString(node)} 1 ${node.owner.padEnd(8)} ${node.group.padEnd(8)} ${String(size).padStart(6)} ${name}`; }
  private cmdCat(args:string[],response:EngineResponse):void { const user=this.requireUser(response);if(!user)return;if(args.length===0)return void response.lines.push("cat: missing operand");for(const arg of args){const path=this.resolvePath(arg,user),node=getNode(this.host,path);if(!node){response.lines.push(`cat: ${arg}: No such file or directory`);continue;}if(node.type!=="file"){response.lines.push(`cat: ${arg}: Is a directory`);continue;}if(!canRead(node,user)){response.lines.push(`cat: ${arg}: Permission denied`);continue;}response.lines.push(...(node.content??"").split("\n"));markFileRead(this.state,this.frame.hostId,path);} }
  private cmdId(response:EngineResponse):void { const user=this.requireUser(response);if(!user)return;const groups=user.groups.map(g=>`${this.host.groups[g]??"?"}(${g})`).join(",");response.lines.push(`uid=${user.uid}(${user.username}) gid=${user.gid}(${user.groups[0]??user.username}) groups=${groups}`); }
  private cmdUname(args:string[],response:EngineResponse):void { response.lines.push(args.includes("-a")?`${this.host.os} ${this.host.hostname} ${this.host.kernel} #13 ${this.host.architecture}`:(this.host.os.split(" ")[0]??this.host.os)); }
  private cmdGrep(args:string[],response:EngineResponse):void { const user=this.requireUser(response);if(!user)return;let insensitive=false;const positional:string[]=[];for(const arg of args){if(arg==="-i")insensitive=true;else positional.push(arg);}if(positional.length<2)return void response.lines.push("usage: grep [-i] PATTERN FILE");const[pattern,fileArg]=positional as [string,string];const path=this.resolvePath(fileArg,user),node=getNode(this.host,path);if(!node||node.type!=="file")return void response.lines.push(`grep: ${fileArg}: No such file`);if(!canRead(node,user))return void response.lines.push(`grep: ${fileArg}: Permission denied`);const needle=insensitive?pattern.toLowerCase():pattern;for(const line of(node.content??"").split("\n")){const haystack=insensitive?line.toLowerCase():line;if(haystack.includes(needle))response.lines.push(line);}markFileRead(this.state,this.frame.hostId,path); }
  private cmdFind(args:string[],response:EngineResponse):void { const user=this.requireUser(response);if(!user)return;let startArg=".";let namePattern:string|undefined;let index=0;if(args[0]&&args[0]!=="-name"){startArg=args[0];index=1;}if(args[index]==="-name"&&args[index+1])namePattern=args[index+1];const start=this.resolvePath(startArg,user),startNode=getNode(this.host,start);if(!startNode)return void response.lines.push(`find: '${startArg}': No such file or directory`);const matcher=namePattern?globToRegExp(namePattern):null;for(const[path,node]of Object.entries(this.host.files).sort(([a],[b])=>a.localeCompare(b))){if(path!==start&&!path.startsWith(start==="/"?"/":`${start}/`))continue;if(matcher&&!matcher.test(basename(path)))continue;if(node.owner!==user.username&&user.uid!==0&&(node.mode&0o004)===0&&node.type==="file")continue;response.lines.push(path);} }
  private cmdPs(_args:string[],response:EngineResponse):void { response.lines.push("USER       PID %CPU %MEM COMMAND");const processes=[...this.host.processes,...(this.state.dynamicProcesses[this.host.id]??[])].sort((a,b)=>a.pid-b.pid);for(const p of processes)response.lines.push(`${p.user.padEnd(9)} ${String(p.pid).padStart(4)} ${(p.cpu??0).toFixed(1).padStart(4)} ${(p.memory??0).toFixed(1).padStart(4)} ${p.command}`); }
  private cmdEnv(response:EngineResponse):void { const u=this.requireUser(response);if(!u)return;response.lines.push(`USER=${u.username}`,`HOME=${u.home}`,`SHELL=${u.shell}`,`HOSTNAME=${this.host.hostname}`,"TERM=vt100","PATH=/usr/local/bin:/usr/bin:/bin"); }
  private cmdSu(args:string[],response:EngineResponse):void { const target=args[0]??"root";if(!this.host.users[target])return void response.lines.push(`su: user ${target} does not exist`);if(this.user?.username===target)return;this.state.mode={kind:"su-password",username:target}; }
  private cmdSudo(args:string[],response:EngineResponse):void { if(args[0]==="-l"){response.lines.push(`User ${this.user?.username??"unknown"} may run the following commands on ${this.host.hostname}:`,`    (none)`);return;}response.lines.push(`${this.user?.username??"user"} is not in the sudoers file. This incident will be reported.`); }
  private resolveHost(name:string):GameHost|undefined { return Object.values(this.world.hosts).find(h=>h.id===name||h.hostname===name||h.aliases.includes(name)); }
  private cmdSsh(args:string[],response:EngineResponse):void { const current=this.requireUser(response);if(!current)return;if(!args[0])return void response.lines.push("usage: ssh [user@]host");const[maybeUser,maybeHost]=args[0].includes("@")?args[0].split("@",2):[current.username,args[0]];const targetHost=this.resolveHost(maybeHost!);if(!targetHost||!this.state.discoveredHosts.includes(targetHost.id))return void response.lines.push(`ssh: Could not resolve hostname ${maybeHost}: Name or service not known`);if(!targetHost.users[maybeUser!])return void response.lines.push(`ssh: ${maybeUser}@${targetHost.hostname}: Permission denied`);this.state.mode={kind:"ssh-password",hostId:targetHost.id,username:maybeUser!}; }
  private cmdExit(response:EngineResponse):void { if(this.state.sessionStack.length>1){const old=this.state.sessionStack.pop()!;response.lines.push(`Connection to ${this.world.hosts[old.hostId]?.hostname??old.hostId} closed.`);this.state.mode={kind:"shell"};return;}this.frame.username=null;this.frame.cwd="/";this.state.mode={kind:"login-user"};response.lines.push("logout",""); }
  private cmdNetstat(response:EngineResponse):void { response.lines.push("Active Internet connections (simulated)","Proto Local Address       Foreign Address     State");for(const neighborId of this.host.neighbors){const host=this.world.hosts[neighborId];if(!host)continue;const visible=this.state.discoveredHosts.includes(host.id);response.lines.push(`tcp   ${this.host.hostname}:22`.padEnd(27)+`${visible?host.hostname:"?.?.?.?"}:22`.padEnd(20)+"ESTABLISHED");} }
  private cmdMail(response:EngineResponse):void { const u=this.requireUser(response);if(!u)return;const path=`/var/mail/${u.username}`,node=getNode(this.host,path);if(!node||node.type!=="file")return void response.lines.push("No mail for you.");if(!canRead(node,u))return void response.lines.push("mail: Permission denied");response.lines.push(...(node.content??"").split("\n"));markFileRead(this.state,this.frame.hostId,path); }
  private cmdSystem(args:string[],response:EngineResponse):void { switch(args[0]??"help"){case"help":response.lines.push("SYSTEM 13 client commands:","  system status","  system save","  system disconnect","  system restart","  system new");break;case"status":response.lines.push("SYSTEM 13 LOCAL SESSION",`RUN ID ............ ${this.world.runId}`,`SCENARIO .......... ${this.world.scenarioId} ${this.world.scenarioVersion}`,`HOST .............. ${this.host.hostname}`,`USER .............. ${this.user?.username??"(login)"}`,`HOSTS DISCOVERED .. ${this.state.discoveredHosts.length}`,`ROOTED HOSTS ...... ${this.state.rootedHosts.length}`,`COMMANDS .......... ${this.state.commandCount}`,`ENDING ............ ${this.state.ending?.title??"not reached"}`);break;case"save":response.systemAction="save";response.lines.push("Writing local session image...");break;case"disconnect":response.systemAction="disconnect";break;case"restart":response.systemAction="restart";break;case"new":response.systemAction="new-confirm";break;default:response.lines.push(`system: unknown command '${args[0]}'`);} }
  private cmdDiagctl(args:string[],response:EngineResponse):void { const u=this.requireUser(response);if(!u)return;if(args.length===0||args.includes("--help")){response.lines.push("Meridian Diagnostic Controller 0.8","usage: diagctl [--status|--debug]","WARNING: debug mode is for factory maintenance only.");return;}if(args.includes("--status")){response.lines.push("storage .... OK","network .... OK","security ... DEGRADED");return;}if(args.includes("--debug")){if(this.host.id!=="archive03")return void response.lines.push("diagctl: debug controller unavailable");if(u.username!=="miller"&&u.uid!==0)return void response.lines.push("diagctl: maintenance account required");const root=this.host.users.root;if(!root)return void response.lines.push("diagctl: root account missing");response.lines.push("DIAGNOSTIC DEBUG CHANNEL ENABLED","Dropping to maintenance context...","");this.frame.username="root";this.frame.cwd=root.home;markRooted(this.state,this.host.id);return;}response.lines.push("diagctl: unknown option"); }
}
