import type { GameHost, GeneratedWorld, ScenarioDefinition, ScenarioVariable, VirtualNode } from "../core/types.js";
import { rngStream, runIdFromSeed } from "../rng/rng.js";
function getPath(value: unknown, path: string): unknown { let current: unknown = value; for (const part of path.split(".")) { if (current === null || typeof current !== "object") return undefined; current = (current as Record<string, unknown>)[part]; } return current; }
function renderString(input: string, context: Record<string, unknown>): string { return input.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (_match, path: string) => { const value = getPath(context, path); if (value === undefined || value === null) return ""; return typeof value === "object" ? JSON.stringify(value) : String(value); }); }
function renderDeep<T>(value: T, context: Record<string, unknown>): T { if (typeof value === "string") return renderString(value, context) as T; if (Array.isArray(value)) return value.map((item) => renderDeep(item, context)) as T; if (value !== null && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, renderDeep(item, context)])) as T; return value; }
function generateVariable(seed: string, name: string, spec: ScenarioVariable): unknown { const rng = rngStream(seed, `variable:${name}`); if (spec.kind === "choice") return rng.pick(spec.values); if (spec.kind === "number") return rng.integer(spec.min, spec.max); const digits = spec.digits ?? 2; const word = rng.pick(spec.words); let suffix = ""; for (let i = 0; i < digits; i += 1) suffix += rng.integer(0, 9).toString(); return `${word}${suffix}`; }
function ensureDirectory(files: Record<string, VirtualNode>, path: string): void { if (files[path]) return; files[path] = { path, type: "dir", owner: "root", group: "root", mode: 0o755 }; }
function buildFileMap(nodes: VirtualNode[]): Record<string, VirtualNode> { const files: Record<string, VirtualNode> = {}; ensureDirectory(files, "/"); for (const node of nodes) { const parts = node.path.split("/").filter(Boolean); let current = ""; for (const part of parts.slice(0, -1)) { current += `/${part}`; ensureDirectory(files, current); } files[node.path] = { ...node }; } return files; }
export function generateWorld(scenario: ScenarioDefinition, seed: string): GeneratedWorld {
  const context: Record<string, unknown> = {};
  for (const [name, spec] of Object.entries(scenario.generation.variables)) context[name] = generateVariable(seed, name, spec);
  const rendered = renderDeep(scenario, context); const hosts: Record<string, GameHost> = {};
  for (const template of rendered.hosts) hosts[template.id] = { id: template.id, hostname: template.hostname, aliases: template.aliases ?? [], os: template.os, kernel: template.kernel, architecture: template.architecture ?? "i386", groups: { ...template.groups }, users: Object.fromEntries(template.users.map((user) => [user.username, { ...user }])), files: buildFileMap(template.files.map((file) => ({ ...file }))), processes: (template.processes ?? []).map((process) => ({ ...process })), services: (template.services ?? []).map((service) => ({ ...service })), neighbors: [...(template.neighbors ?? [])], commands: [...(template.commands ?? [])] };
  return { schemaVersion: 1, scenarioId: rendered.id, scenarioVersion: rendered.version, title: rendered.title, company: rendered.company, seed, runId: runIdFromSeed(seed), startHostId: rendered.startHostId, banner: rendered.banner, generation: context, hosts, events: rendered.events ?? [] };
}
