import type { RunSave } from "../core/types.js";
const DB_NAME = "system13"; const STORE_NAME = "runs"; const CURRENT_KEY = "current"; const FALLBACK_KEY = "system13.current";
function openDatabase(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(STORE_NAME)) db.createObjectStore(STORE_NAME); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("unable to open save database")); }); }
export class SaveStore {
  private db: IDBDatabase | null = null;
  async init(): Promise<void> { try { this.db = await openDatabase(); } catch { this.db = null; } }
  async load(): Promise<RunSave | null> { if (!this.db) { const raw = localStorage.getItem(FALLBACK_KEY); return raw ? JSON.parse(raw) as RunSave : null; } return new Promise((resolve, reject) => { const transaction = this.db!.transaction(STORE_NAME, "readonly"); const request = transaction.objectStore(STORE_NAME).get(CURRENT_KEY); request.onsuccess = () => resolve((request.result as RunSave | undefined) ?? null); request.onerror = () => reject(request.error ?? new Error("unable to read save")); }); }
  async save(save: RunSave): Promise<void> { const value = structuredClone(save); value.updatedAt = new Date().toISOString(); if (!this.db) { localStorage.setItem(FALLBACK_KEY, JSON.stringify(value)); return; } await new Promise<void>((resolve, reject) => { const transaction = this.db!.transaction(STORE_NAME, "readwrite"); transaction.objectStore(STORE_NAME).put(value, CURRENT_KEY); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error ?? new Error("unable to save run")); }); }
  async clear(): Promise<void> { localStorage.removeItem(FALLBACK_KEY); if (!this.db) return; await new Promise<void>((resolve, reject) => { const transaction = this.db!.transaction(STORE_NAME, "readwrite"); transaction.objectStore(STORE_NAME).delete(CURRENT_KEY); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error ?? new Error("unable to delete save")); }); }
}
